### ISSUE TITLE
Auto-check "PathName_" & "FileName_"

### ISSUE THREAD

**Issue by hmbotelho** [tischi/HTM_Explorer#21]
Feature request:

Warn the user if the image table does not contain matching "image_filename" and "image_foldername" columns. If the columns are not there the "Click&View" feature does not work.

![image](https://cloud.githubusercontent.com/assets/7735703/17028976/4f2a1b6e-4f61-11e6-9fa2-a35621dd0014.png)

Thanks!

**Comment by tischi** [comment]
@hmbotelho 
If you use click&view and the columns do not exist it shows now an error message.
Could you please try it out?

**Comment by hmbotelho** [comment]
@tischi 
Yes, it works. Thanks Tischi!

![image](https://cloud.githubusercontent.com/assets/7735703/17310545/0e1ddf04-583d-11e6-9566-20c44c73e276.png)
