### ISSUE TITLE
separation of gui and "compute" code in gui.R

### ISSUE THREAD

**Issue by VolkerH** [tischi/HTM_Explorer#23]
There are several instances in gui.R where the gui handler does more than calling the  appropriate function, e.g. looping over measurements or features. It would be cleaner to move these loops into the appropriate functions in functions.R that do the computation and have the functions in gui.R being pure GUI-callback handlers.

**Comment by tischi** [comment]
good point! I will have a look!

**Comment by tischi** [comment]
@VolkerH 

I changed:
- guiHandler_Normalisation
- htmNormalization
  such that the loop over the measurements is now in htmNormalization.

Shall I change more?

**Comment by tischi** [comment]
done
